[package]
name = "cosmo_cli"
version = "0.0.1"
description = "Easy Cosmo pipeline helper"
authors = [
    "banditopazzo <banditopazzo@gmail.com>",
    "Gianluigi <gianluigi@exein.io>",
]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "cosmo"

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
rpassword = "6.0.1"
serde = { version = "1.0.136", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["json", "multipart"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4.19", features = ["serde"] }
dirs = "4.0.0"
jsonwebtoken = "8"
term-table = "1.3.2"
serde_json = "1.0.79"
uuid = { version = "1.0.0", features = ["serde", "v4"] }
lazy_static = "1.4.0"
log = "0.4"
env_logger = "0.9.0"
openssl-probe = "0.1.5"
openssl = { version = '0.10.38' }
semver = { version = "1.0.7", features = ["serde"] }
async-trait = "0.1.53"
human-panic = "1.0.3"
anyhow = "1.0"
clap-verbosity-flag = "1.0.0"

[features]
default = ["aws"]
vendored-openssl = ['openssl/vendored'] # Statically include openssl
# ENVs
aws = []
staging = []
development = []

[profile.release]
lto = true        # Enable Link Time Optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = 'abort'   # Abort on panic
