[package]
name = "efa_cli"
version = "0.0.1"
authors = ["banditopazzo <banditopazzo@gmail.com>", "Gianluigi <gianluigi@exein.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "efa"

[dependencies]
clap = "2.33.3"
rpassword = "5.0.0"
serde = { version = "1.0.116", features = ["derive"] }
reqwest = { version = "0.11.0", features = ["json", "multipart"] }
http = "0.2.1"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4.19", features = ["serde"] }
dirs = "3.0"
jsonwebtoken = "7.2.0"
term-table = "1.3.0"
num_enum = "0.5.1"
serde_yaml = "0.8"
serde_json = "1.0"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
num_cpus = "1.13.0"
flate2 = "1.0.14"
tar = "0.4.30"
tempfile = "3.1.0"
lazy_static = "1.4.0"
log = "0.4.13"
env_logger = "0.8.2"
zip = "0.5.9"
ctrlc = "3.1.7"
openssl-probe = "0.1.2"
openssl = { version = '0.10.32', optional = true, features = ["vendored"] }
semver = { version = "0.11.0", features = ["serde"] }
nom = "6.0.1"
csv = "1.1.5"
git2 = "0.13"
async-trait = "0.1.48"
regex = "1.4.5"
human-panic = "1.0.3"

[dev-dependencies]
hex = "0.4.2"

[features]
vendored-openssl = ['openssl/vendored'] # Statically include openssl
static-filters = []                     # Enable filters

[profile.release]
opt-level = 's' # Optimize for size
# opt-level = 3 # Optimize for performance
lto = true # Enable Link Time Optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = 'abort' # Abort on panic
