[package]
name = "cosmo_cli"
version = "0.0.1"
description = "Easy Cosmo pipeline helper"
authors = [
    "banditopazzo <banditopazzo@gmail.com>",
    "Gianluigi <gianluigi@exein.io>",
]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "cosmo"