[package]
name = "efa_cli"
version = "0.0.1"
authors = ["banditopazzo <banditopazzo@gmail.com>", "Gianluigi <gianluigi@exein.io>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "efa"

[dependencies]
clap = "2.33.3"
rpassword = "5.0.1"
serde = { version = "1.0.126", features = ["derive"] }
reqwest = { version = "0.11.4", features = ["json", "multipart"] }
http = "0.2.4"
tokio = { version = "1.8.2", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4.19", features = ["serde"] }
dirs = "3.0.2"
jsonwebtoken = "7.2.0"
term-table = "1.3.1"
serde_json = "1.0.64"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
lazy_static = "1.4.0"
log = "0.4.14"
env_logger = "0.9.0"
openssl-probe = "0.1.2"
semver = { version = "1.0.3", features = ["serde"] }
nom = "6.2.1"
async-trait = "0.1.50"
human-panic = "1.0.3"


[profile.release]
opt-level = 's' # Optimize for size
lto = true # Enable Link Time Optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = 'abort' # Abort on panic
