name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
          - debug
          - release

        platform:
          - target: x86_64-unknown-linux-gnu
            args: ""

          # For `musl` builds openssl must be vendored
          - target: x86_64-unknown-linux-musl
            args: "--features openssl-vendored"

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.platform.target }}

      - name: Install musl-gcc
        if: ${{ endsWith(matrix.platform.target, 'musl') }}
        run: sudo apt install -y musl-tools

      - name: Build Debug
        if: ${{ matrix.profile == 'debug' }} 
        run: cargo build --locked --target=${{ matrix.platform.target }} --workspace --all-targets ${{ matrix.platform.args }}

      - name: Build Release
        if: ${{ matrix.profile == 'release' }} 
        run: cargo build --locked --target=${{ matrix.platform.target }} --workspace --all-targets ${{ matrix.platform.args }} --release

      - name: Check build did not modify any files
        run: test -z "$(git status --porcelain)"
